### ISSUE TITLE
Use of the words "playbook" and "plays"

### ISSUE THREAD

**Issue by jmarsicano** [usds/playbook#204]
The words "playbook" and "plays" exclude women by using a football analogy (which only men play), and go against plain language by leaving out anyone else (like new Americans) who doesn't get the analogy.   

Neutral, user-friendly words like "handbook," "guide," or "guidebook" - with "tips" or "guidelines" (instead of "plays") would include everyone, and follow plain language. 

Please consider changing the title and section headings of this content. 

Thanks for your consideration.

**Comment by m-hsiang** [comment]
Fwiw, I (a woman) played soccer and ultimate frisbee, both internationally, and both of which have a playbook and plays.

I find the term playbook to be the right combination of directive and lighthearted.  Your terms are also good descriptions and good terms, but I for one would like to note that it's not really a gendered term.



On: 27 June 2017 19:12, "jmarsicano" <notifications@github.com> wrote:

The words "playbook" and "plays" exclude women by using a football analogy (which only men play), and go against plain language by leaving out anyone else (like new Americans) who doesn't get the analogy.

Neutral, user-friendly words like "handbook," "guide," or "guidebook" - with "tips" or "guidelines" (instead of "plays") would include everyone, and follow plain language.

Please consider changing the title and section headings of this content.

Thanks for your consideration.

**Comment by jmarsicano** [comment]
I can’t argue with your experience and there’s room for more than one interpretation of the “male only” argument.

That aside, should someone have to understand a sports analogy to understand your content?

Jo Marsicano
Center of Innovation and Excellence
701 Building (701 South 4th Street)
612-348-3105
MC L605
jo.marsicano@hennepin.us<mailto:jo.marsicano@hennepin.us> | hennepin.us<http://www.hennepin.us/>

[Hennepin County logo]

**Comment by lheyman** [comment]
I don't think one needs to understand sports to understand the correlation between actions and outcomes. The "Plays" in this context denote actions toward specific outcomes. "Tips," "guides," etc. by comparison are passive terms, not necessarily toward any particular outcome.

In other words, I see this more as a co-opting/assimilating of a sports term rather than simply metaphor.

**Comment by jmarsicano** [comment]
You must understand sports to understand “playbook” and, in this context, “play.” They’re sports terms.

Have you tested these terms on real users? If so, and they went for it, great. Argument over.  But if not, I suggest it.


Jo Marsicano
Center of Innovation and Excellence
701 Building (701 South 4th Street)
612-348-3105
MC L605
jo.marsicano@hennepin.us<mailto:jo.marsicano@hennepin.us> | hennepin.us<http://www.hennepin.us/>

[Hennepin County logo]

**Comment by lheyman** [comment]
Google searching "playbook" yields no sports-related links until the middle of the second page of results (and the second one doesn't appear until the 4th page)

Google search "playbook example" and now you're on page 5 before the first sports hit.

All of the major dictionary sites (when you Google search "playbook dictionary") list at least one (usually more) non-sports-related definition. E.g. "any plan or set of strategies, as for outlining a campaign in business or politics." (dictionary.com), or "a stock of usual tactics or methods" (merriam-webster.com).

Given the above, I think it's fair to say the term has transcended its roots, and thus is, in fact, plain language. Further, I take the fact that most of the top hits are all technology or business-related as validation that "playbook" is the correct title for the contents of this repo.
 
(Also, FWIW, plenty of women play American Football: https://en.wikipedia.org/wiki/Women%27s_American_football)

Can we close?

**Comment by jmarsicano** [comment]
Google results have to be taken with a grain of salt, since Google is never an objective source, for anything. But you’ve cited dictionary sites, which do have credibility. I’d say user testing would be the sure-fire way to test the perception and comprehension of the word.

In terms of women playing football, sure, there are some that do, but overwhelmingly it’s men.

We can close the discussion, per your request.


Jo Marsicano
Center of Innovation and Excellence
701 Building (701 South 4th Street)
612-348-3105
MC L605
jo.marsicano@hennepin.us<mailto:jo.marsicano@hennepin.us> | hennepin.us<http://www.hennepin.us/>

[Hennepin County logo]

**Comment by waldoj** [comment]
I frequently refer to a couple of different playbooks, and I _never knew until right now_ that "playbook" was a word rooted in sports. At no point was I confused by the meaning of this term, given the context of the thing I was looking at.

I am a man.

**Comment by jhamon** [comment]
I don't think this issue will be moved closer to resolution by having more people saying "As an X, I think Y". But I'll chime in anyway with my 2 cents.

As a female engineer, I agree "playbook" is a perfectly fine word that accurately describes the purpose and content of this repository. Even if "play" were explicitly and exclusively a sports term, which it is not, women also play team sports and are exposed to them in popular culture. So I fail to see how this language excludes women. The idea that somehow women can't use or understand common words that have been tainted by association with sports actually seems like the only problematic thing in this thread.
